apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: microservice-demo
    component: apache
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apache
  template:
    metadata:
      labels:
        run: apache
    spec:
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-apache:latest
        name: apache
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: microservice-demo
    component: catalog
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      run: catalog
  template:
    metadata:
      labels:
        run: catalog
    spec:
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-catalog:latest
        name: catalog
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: microservice-demo
    component: customer
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      run: customer
  template:
    metadata:
      labels:
        run: customer
    spec:
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-customer:latest
        name: customer
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: microservice-demo
    component: order
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      run: order
  template:
    metadata:
      labels:
        run: order
    spec:
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-order:latest
        name: order
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: microservice-demo
    component: apache
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: apache
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: microservice-demo
    component: catalog
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: catalog
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: microservice-demo
    component: customer
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: customer
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: microservice-demo
    component: order
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: order
