apiVersion: v1
entries:
  microservice-demo:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-03-03T15:14:42.5495354-08:00"
    description: A Helm chart for microservice demo application
    digest: 82e860aaadae05388320877c1ab962ab37e249e998abec784a1dd93e1aa70ee8
    name: microservice-demo
    type: application
    urls:
    - https://ta-ny.github.io/microservices/charts/microservice-demo-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-03-03T15:14:42.5479108-08:00"
    description: A Helm chart for microservice demo application
    digest: 74dde91635e262e91f05f9a6bd522aead0a7490c3ba0976277dd35cfaf8c11e1
    name: microservice-demo
    type: application
    urls:
    - https://ta-ny.github.io/microservices/charts/microservice-demo-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-03T15:14:42.5435019-08:00"
