apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-check
  labels:
    app: sync-check
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sync-check
  template:
    metadata:
      labels:
        app: sync-check
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sync-check
  labels:
    app: sync-check
spec:
  type: ClusterIP
  selector:
    app: sync-check
  ports:
    - name: http
      port: 80
      targetPort: 80